# Generated by Django 3.2 on 2021-06-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('title', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
