# Generated by Django 3.2 on 2021-06-28 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caos_news_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
