# Generated by Django 3.2 on 2021-06-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caos_news_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='title',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='new',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='new',
            name='ciudad',
            field=models.CharField(default='ciudad', max_length=50),
        ),
        migrations.AddField(
            model_name='new',
            name='documento',
            field=models.CharField(default='documento', max_length=50),
        ),
        migrations.AddField(
            model_name='new',
            name='email',
            field=models.CharField(default='email', max_length=50),
        ),
        migrations.AddField(
            model_name='new',
            name='noticia',
            field=models.TextField(default='email', max_length=50),
        ),
        migrations.AddField(
            model_name='new',
            name='rut',
            field=models.CharField(default='rut', max_length=50),
        ),
        migrations.AddField(
            model_name='new',
            name='telefono',
            field=models.CharField(default='telefono', max_length=50),
        ),
    ]
