# Generated by Django 3.2 on 2021-06-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caos_news_web', '0003_alter_new_noticia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='rut',
        ),
        migrations.AddField(
            model_name='new',
            name='pasaporte',
            field=models.CharField(default='pasaporte', max_length=50),
        ),
    ]
